apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: svdgqlet2-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:af734f0a88168ea8114cdd6c07ea2c79a2390730@sha256:6d21355583968d09ed2ad845733a0b94797775c44a10c441b9a6c781f6c8831d
          name: container-image
